-- 1. Spam Keywords Table
create table if not exists spam_keywords (
  id bigint generated by default as identity primary key,
  keyword text not null unique,
  weight int default 10, -- 1 to 100 severity
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Scan History Table (REMOVED)
-- create table if not exists scan_history ...


-- 3. Calculate Dot Score RPC
-- This function encapsulates the logic on the server side correctly.
create or replace function calculate_dot_score(
  msg_body text,
  google_raw jsonb default '{}'::jsonb,
  vt_raw jsonb default '{}'::jsonb,
  target_url text default null
) returns int
language plpgsql
security definer
as $$
declare
  final_score int := 0;
  keyword_score int := 0;
  vt_score int := 0;
  google_score int := 0;
  rec record;
begin
  -- A. Check Spam Keywords (Simple containment check)
  for rec in select weight from spam_keywords where msg_body ilike '%' || keyword || '%' loop
    keyword_score := keyword_score + rec.weight;
  end loop;
  
  -- Cap keyword score at 60
  if keyword_score > 60 then keyword_score := 60; end if;

  -- B. Parse VirusTotal Result (Example Logic)
  -- Assuming vt_raw has 'positives' count
  if (vt_raw->>'positives')::int > 0 then
    vt_score := 100; -- Immediate Danger
  end if;

  -- C. Parse Google Safe Browsing Result
  -- Assuming google_raw is not empty on threat found
  if google_raw != '{}'::jsonb then
     google_score := 80;
  end if;

  -- D. Calculate Final Score (Max of components)
  final_score := greatest(keyword_score, vt_score, google_score);
  
  -- Cap at 100
  if final_score > 100 then final_score := 100; end if;

  -- E. Save History (REMOVED per user request)
  -- insert into scan_history (target_content, is_url, dot_score)
  -- values (coalesce(target_url, msg_body), target_url is not null, final_score);

  return final_score;
end;
$$;

-- 4. Clean Phone (Verified Organizations) - Mapped to 'public.contact_list'
-- Note: The actual table is 'contact_list' with columns: 기관명, 부서명, clean_phone, 전화번호, 팩스번호, 주소
-- We do not create the table here as it already exists in the user's DB. 
-- We just define the RPC/Policies.

-- RPC for searching clean phone (contact_list)
create or replace function search_clean_phone(
  p_phone_number text
) returns jsonb
language plpgsql
security invoker -- User requested invoker
as $$
declare
  result record;
begin
  -- Search in contact_list using 'clean_phone' column.
  -- We strip the input to match the clean format (no hyphens).
  
  select "기관명" as org_name, "부서명" as dept_name, "전화번호" as phone_number, "팩스번호" as fax_number, "주소" as address
  into result
  from contact_list
  where "clean_phone" = replace(p_phone_number, '-', '')
  limit 1;

  if found then
    return jsonb_build_object(
      'found', true,
      'org_name', result.org_name,
      'dept_name', result.dept_name,
      'phone_number', result.phone_number,
      'fax_number', result.fax_number,
      'address', result.address
    );
  else
    return jsonb_build_object('found', false);
  end if;
end;
$$;

-- 5. Security (RLS)
-- Enable RLS on tables
alter table spam_keywords enable row level security;
-- alter table scan_history enable row level security; -- Removed
-- contact_list might already have RLS, ensuring it is enabled
alter table contact_list enable row level security;

-- Policies for spam_keywords
drop policy if exists "Allow public read access to spam_keywords" on spam_keywords;
create policy "Allow public read access to spam_keywords"
  on spam_keywords for select
  to anon, authenticated
  using (true);

drop policy if exists "Allow only admin to modify spam_keywords" on spam_keywords;
create policy "Allow only admin to modify spam_keywords"
  on spam_keywords for all
  to service_role
  using (true)
  with check (true);

-- Policies for scan_history (REMOVED)
-- drop policy if exists "Allow anonymous insert access to scan_history" on scan_history;
-- drop policy if exists "Allow only admin to read scan_history" on scan_history;

-- Policies for contact_list
-- Allow public read access
drop policy if exists "Allow public read access to contact_list" on contact_list;
create policy "Allow public read access to contact_list"
  on contact_list for select
  to anon, authenticated
  using (true);



