-- 1. Spam Keywords Table
create table if not exists spam_keywords (
  id bigint generated by default as identity primary key,
  keyword text not null unique,
  weight int default 10, -- 1 to 100 severity
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Scan History Table (Cache)
create table if not exists scan_history (
  id bigint generated by default as identity primary key,
  target_content text not null, -- URL or Message Body
  is_url boolean default false,
  dot_score int not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index for fast lookup
create index if not exists idx_scan_history_content on scan_history(target_content);

-- 3. Calculate Dot Score RPC
-- This function encapsulates the logic on the server side correctly.
create or replace function calculate_dot_score(
  msg_body text,
  google_raw jsonb default '{}'::jsonb,
  vt_raw jsonb default '{}'::jsonb,
  target_url text default null
) returns int
language plpgsql
security definer
as $$
declare
  final_score int := 0;
  keyword_score int := 0;
  vt_score int := 0;
  google_score int := 0;
  rec record;
begin
  -- A. Check Spam Keywords (Simple containment check)
  for rec in select weight from spam_keywords where msg_body ilike '%' || keyword || '%' loop
    keyword_score := keyword_score + rec.weight;
  end loop;
  
  -- Cap keyword score at 60
  if keyword_score > 60 then keyword_score := 60; end if;

  -- B. Parse VirusTotal Result (Example Logic)
  -- Assuming vt_raw has 'positives' count
  if (vt_raw->>'positives')::int > 0 then
    vt_score := 100; -- Immediate Danger
  end if;

  -- C. Parse Google Safe Browsing Result
  -- Assuming google_raw is not empty on threat found
  if google_raw != '{}'::jsonb then
     google_score := 80;
  end if;

  -- D. Calculate Final Score (Max of components)
  final_score := greatest(keyword_score, vt_score, google_score);
  
  -- Cap at 100
  if final_score > 100 then final_score := 100; end if;

  -- E. Save History (Optional optimization: only save if score > 0 or unique)
  -- For now, we save everything to build a dataset.
  insert into scan_history (target_content, is_url, dot_score)
  values (coalesce(target_url, msg_body), target_url is not null, final_score);

  return final_score;
end;
$$;
