-- 1. Spam Keywords Table
create table if not exists spam_keywords (
  id bigint generated by default as identity primary key,
  keyword text not null unique,
  weight int default 10, -- 1 to 100 severity
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Scan History Table (Cache)
create table if not exists scan_history (
  id bigint generated by default as identity primary key,
  target_content text not null, -- URL or Message Body
  is_url boolean default false,
  dot_score int not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index for fast lookup
create index if not exists idx_scan_history_content on scan_history(target_content);

-- 3. Calculate Dot Score RPC
-- This function encapsulates the logic on the server side correctly.
create or replace function calculate_dot_score(
  msg_body text,
  google_raw jsonb default '{}'::jsonb,
  vt_raw jsonb default '{}'::jsonb,
  target_url text default null
) returns int
language plpgsql
security definer
as $$
declare
  final_score int := 0;
  keyword_score int := 0;
  vt_score int := 0;
  google_score int := 0;
  rec record;
begin
  -- A. Check Spam Keywords (Simple containment check)
  for rec in select weight from spam_keywords where msg_body ilike '%' || keyword || '%' loop
    keyword_score := keyword_score + rec.weight;
  end loop;
  
  -- Cap keyword score at 60
  if keyword_score > 60 then keyword_score := 60; end if;

  -- B. Parse VirusTotal Result (Example Logic)
  -- Assuming vt_raw has 'positives' count
  if (vt_raw->>'positives')::int > 0 then
    vt_score := 100; -- Immediate Danger
  end if;

  -- C. Parse Google Safe Browsing Result
  -- Assuming google_raw is not empty on threat found
  if google_raw != '{}'::jsonb then
     google_score := 80;
  end if;

  -- D. Calculate Final Score (Max of components)
  final_score := greatest(keyword_score, vt_score, google_score);
  
  -- Cap at 100
  if final_score > 100 then final_score := 100; end if;

  -- E. Save History (Optional optimization: only save if score > 0 or unique)
  -- For now, we save everything to build a dataset.
  insert into scan_history (target_content, is_url, dot_score)
  values (coalesce(target_url, msg_body), target_url is not null, final_score);

  return final_score;
end;
$$;

-- 4. Clean Phone (Verified Organizations)
create table if not exists clean_phone (
  id bigint generated by default as identity primary key,
  org_name text not null,
  dept_name text,
  phone_number text not null unique,
  fax_number text,
  address text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index for phone search
create index if not exists idx_clean_phone_number on clean_phone(phone_number);

-- RPC for searching clean phone
create or replace function search_clean_phone(
  p_phone_number text
) returns jsonb
language plpgsql
security definer
as $$
declare
  result record;
begin
  select org_name, dept_name, phone_number, fax_number, address
  into result
  from clean_phone
  where phone_number = p_phone_number
  limit 1;

  if found then
    return jsonb_build_object(
      'found', true,
      'org_name', result.org_name,
      'dept_name', result.dept_name,
      'phone_number', result.phone_number,
      'fax_number', result.fax_number,
      'address', result.address
    );
  else
    return jsonb_build_object('found', false);
  end if;
end;
$$;

-- 5. Security (RLS)
-- Enable RLS on tables
alter table spam_keywords enable row level security;
alter table scan_history enable row level security;
alter table clean_phone enable row level security;

-- Policies for spam_keywords
-- Anyone can see keywords (useful for client-side hint/preview if needed)
drop policy if exists "Allow public read access to spam_keywords" on spam_keywords;
create policy "Allow public read access to spam_keywords"
  on spam_keywords for select
  to anon, authenticated
  using (true);

-- Only service_role or admin can modify keywords
drop policy if exists "Allow only admin to modify spam_keywords" on spam_keywords;
create policy "Allow only admin to modify spam_keywords"
  on spam_keywords for all
  to service_role
  using (true)
  with check (true);

-- Policies for scan_history
-- Allow anonymous/authenticated users to insert via RPC (security definer handles this)
drop policy if exists "Allow anonymous insert access to scan_history" on scan_history;
create policy "Allow anonymous insert access to scan_history"
  on scan_history for insert
  to anon, authenticated
  with check (true);

-- Prevent public from reading others' scan history
drop policy if exists "Allow only admin to read scan_history" on scan_history;
create policy "Allow only admin to read scan_history"
  on scan_history for select
  to service_role
  using (true);

-- Policies for clean_phone
-- Allow public read
drop policy if exists "Allow public read access to clean_phone" on clean_phone;
create policy "Allow public read access to clean_phone"
  on clean_phone for select
  to anon, authenticated
  using (true);

-- Only admin modify
drop policy if exists "Allow only admin to modify clean_phone" on clean_phone;
create policy "Allow only admin to modify clean_phone"
  on clean_phone for all
  to service_role
  using (true)
  with check (true);


